// English, en-US
// This file was auto-generated by Quasalang

export default {

	// Общие
	'failed': `Action failed`,
	'success': `Action was successful`,
	'blank': ` `,
	'close': `Close`,
	'ok': `Ok`,
	'cancel': `Cancel`,
	'save': `Save`,
	'edit': `Edit`,
	'delete': `Delete`,
	'control': `Control`,
	'created': `Created`,
	'searchByName': `Search by name`,
	'searchByEmail': `Search by email`,
	'name': `Name`,
	'deleteRecord': `Delete record`,
	'delete': `Delete`,
	'Unauthorized': `User is not authorized`,
	'description': `Description`,
	'Yes': `Yes`,
	'No': `No`,
	'order': `Order`,
	'startDate': `Start date`,
	'endDate': `End date`,

	// Ссылки
	'administrator': `Administrator`,
	'userList': `Users list`,
	'diagnostic': `Diagnostic`,
	'profile': `User profile`,
	'aquadoctor': `Aquadoctor programs`,
	'breathing': `Breathing programs`,
	'orderedPrograms': `Ordered programs`,
	'orderedAquadoctor': `Aquadoctor`,
	'orderedBreathing': `Breathing exercise`,
	'aquadoctorOrder': `Order Aquadoctor programs`,
	'orders': `Orders`,
	'YouOrders': `You orders`,
	'download': `Download`,
	'breathingOrder': `Calculation of breathing exercises`,

	// Логин-регистрация
	"signin-title": `Login to your account`,
	"signup-title": `Account registration`,
	"signin": `Sign in`,
	"signup": `Sign up`,
	"signout": `Sign out`,
	"email": `Email`,
	"enter-email": `Enter your email`,
	"repeat password": `repeat password`,
	"password": `Password`,
	"create-password": `Create a password`,
	"firstname": `First name`,
	"lastname": `Last name`,
	'middlename': `Middle name`,
	"gender": `Gender`,
	'birthday': `Birthday`,

	// Диагностика
	'diagnosticList': `Users diagnostic`,

	// Пользователь
	'userProfile': `User profile`,
	'userName': `User name`,
	'role': `Role`,
	'ActiveState': `Activation`,

	// Музыка
	'MusikAlreadyExists': `The music file has already been uploaded.`,
	'MusikAdded': `Music file added successfully!`,
	'musikName': `Programs name`,

	// Валидация полей ввода
	"required": `Field is required`,
	"email-failed": `Email is failed`,

	// Ответы сервера
	'UserNotFound': `User not found`,
	'EmailAlwaysExists': `A user with this email is already registered`,
	'BadUserPassword': `Wrong password`,
	'MusikNotFound': `Program not found`,
	'LastDiagnosticNotFound': `No diagnostic data`,

	// Загрузка файлов
	'DeleteDownloadedFiles': `Delete downloaded files`,
	'ClearFiles': `Clear`,
	'UploadingFile': `Uploading file`,
	'SelectFile': `Select file`,
	'UploadFile': `Upload file`,
	'AbortUpload': `Abort upload`,

	// Таблицы
	'RowsPerPage': `Rows per page`,
	'NoData': `No data`,

	// Aquadoctor
	'AquadoctorEdit': `Aquadoctor order edit`,
	'color1': `Top color`,
	'color2': `Medium color`,
	'color3': `Bottom color`,
	'upTime': `Time of recruitment`,
	'constTime': `Delay time`,
	'downTime': `Decay time`,
	'speed': `Speed`,
}