// Русский, ru
// This file was auto-generated by Quasalang

export default {

	// Общие
	"failed": `Действие не выполнено.`,
	"success": `Действие прошло успешно`,

	// Логин-регистрация
	"signin-title": `Вход в учетную запись`,
	"signup-title": `Регистрация учетной записи`,
	"signin": `Войти`,
	"signup": `Регистрация`,
	"signout": `Выйти`,
	"email": `Адрес эл. почты`,
	"enter-email": `Введите адрес эл. почты`,
	"repeat password": `повторите пароль`,
	"password": `Пароль`,
	"create-password": `Введите пароль`,
	"firstname": `Имя`,
	"lastname": `Фамилия`,
	"gender": `Пол`,

	// Валидация полей ввода
	"required": `Поле, обязательное для заполнения`,
	"email-failed": `Неправильный адрес эл. почты`,

	// Ответы сервера
	"UserNotFound": `Пользователь не найден`,
	"EmailAlwaysExists": `Пользователь с таким email уже зарегестрирован`,
	"BadUserPassword": `Неправильный пароль`,
}