// Русский, ru
// This file was auto-generated by Quasalang

export default {

	// Общие
	"failed": `Действие не выполнено.`,
	"success": `Действие прошло успешно`,
	'close': `Заурыть`,
	'ok': `Ok`,
	'cancel': `Отмена`,
	'save': `Сохранить`,
	'control': `Управление`,
	'created': `Дата создания`,
	'searchByName': `Поиск по имени`,
	'searchByEmail': `Поиск по email`,
	'name': `Наименование`,
	'deleteRecord': `Удалить запись`,
	'delete': `Удалить`,
	'Unauthorized': `Пользователь не авторизован`,
	'description': `Описание`,

	// Ссылки
	'administrator': `Администратор`,
	'userList': `Список пользователей`,
	'diagnostic': `Диагностика`,
	'profile': `Профиль пользователя`,
	'aquadoctor': `Программы Aquadoctor`,
	'breathing': `Программы Breathing`,
	'orderedPrograms': `Заказанные программы`,
	'orderedAquadoctor': `Aquadoctor`,
	'orderedBreathing': `Дыхательные упражнения`,
	'orders': `Заказы`,

	// Логин-регистрация

	"signin-title": `Вход в учетную запись`,
	"signup-title": `Регистрация учетной записи`,
	"signin": `Войти`,
	"signup": `Регистрация`,
	"signout": `Выйти`,
	"email": `Адрес эл. почты`,
	"enter-email": `Введите адрес эл. почты`,
	"repeat password": `повторите пароль`,
	"password": `Пароль`,
	"create-password": `Введите пароль`,
	"firstname": `Имя`,
	"lastname": `Фамилия`,
	'middlename': `Отчество`,
	"gender": `Пол`,
	'birthday': `Дата рождения`,

	// Диагностика
	'diagnosticList': `Диагностика пользователя`,

	// Пользователь
	'userProfile': `Профиль пользователя`,
	'userName': `Имя пользователя`,
	'role': `Роль`,

	// Музыка
	'MusikAlreadyExists': `Музыкальный файл уже был зыгружен`,
	'MusikAdded': `Музыкальный файл успешно добавлен!`,
	'musikName': `Название программы`,

	// Валидация полей ввода
	"required": `Поле, обязательное для заполнения`,
	"email-failed": `Неправильный адрес эл. почты`,

	// Ответы сервера
	"UserNotFound": `Пользователь не найден`,
	"EmailAlwaysExists": `Пользователь с таким email уже зарегестрирован`,
	"BadUserPassword": `Неправильный пароль`,
}