// Русский, ru
// This file was auto-generated by Quasalang

export default {

	// Общие
	'failed': `Действие не выполнено.`,
	'success': `Действие прошло успешно`,
	'blank': ` `,
	'close': `Закрыть`,
	'ok': `Ok`,
	'cancel': `Отмена`,
	'save': `Сохранить`,
	'edit': `Редактировать`,
	'delete': `Удалить`,
	'control': `Управление`,
	'created': `Дата создания`,
	'searchByName': `Поиск по имени`,
	'searchByEmail': `Поиск по email`,
	'name': `Наименование`,
	'deleteRecord': `Удалить запись`,
	'delete': `Удалить`,
	'Unauthorized': `Пользователь не авторизован`,
	'description': `Описание`,
	'Yes': `Да`,
	'No': `Нет`,
	'order': `Заказать`,
	'startDate': `Дата старта`,
	'endDate': `Дата окончания`,

	// Ссылки
	'administrator': `Администратор`,
	'userList': `Список пользователей`,
	'diagnostic': `Диагностика`,
	'profile': `Профиль пользователя`,
	'aquadoctor': `Программы Aquadoctor`,
	'breathing': `Программы Breathing`,
	'orderedPrograms': `Заказанные программы`,
	'orderedAquadoctor': `Aquadoctor`,
	'orderedBreathing': `Дыхательное упражнение`,
	'aquadoctorOrder': `Заказ программ Aquadoctor`,
	'orders': `Заказы`,
	'YouOrders': `Ваши заказы`,
	'download': `Скачать`,
	'breathingOrder': `Расчет дыхательной имнастики`,

	// Логин-регистрация
	"signin-title": `Вход в учетную запись`,
	"signup-title": `Регистрация учетной записи`,
	"signin": `Войти`,
	"signup": `Регистрация`,
	"signout": `Выйти`,
	"email": `Адрес эл. почты`,
	"enter-email": `Введите адрес эл. почты`,
	"repeat password": `повторите пароль`,
	"password": `Пароль`,
	"create-password": `Введите пароль`,
	"firstname": `Имя`,
	"lastname": `Фамилия`,
	'middlename': `Отчество`,
	"gender": `Пол`,
	'birthday': `Дата рождения`,

	// Диагностика
	'diagnosticList': `Диагностика пользователя`,

	// Пользователь
	'userProfile': `Профиль пользователя`,
	'userName': `Имя пользователя`,
	'role': `Роль`,
	'ActiveState': `Активация`,

	// Музыка
	'MusikAlreadyExists': `Музыкальный файл уже был зыгружен`,
	'MusikAdded': `Музыкальный файл успешно добавлен!`,
	'musikName': `Название программы`,

	// Валидация полей ввода
	"required": `Поле, обязательное для заполнения`,
	"email-failed": `Неправильный адрес эл. почты`,

	// Ответы сервера
	'UserNotFound': `Пользователь не найден`,
	'EmailAlwaysExists': `Пользователь с таким email уже зарегестрирован`,
	'BadUserPassword': `Неправильный пароль`,
	'MusikNotFound': `Программа не найдена`,
	'LastDiagnosticNotFound': `Нет данных диагностики`,

	// Загрузка файлов
	'DeleteDownloadedFiles': `Удалить загруженные файлы`,
	'ClearFiles': `Очистить`,
	'UploadingFile': `Загрузка файла`,
	'SelectFile': `Выбрать файл`,
	'UploadFile': `Загрузить файл`,
	'AbortUpload': `Отмена загрузки`,

	// Таблицы
	'RowsPerPage': `Строк на странице`,
	'NoData': `Нет данных`,

	// Aquadoctor
	'AquadoctorEdit': `Редактирование заказа Aquadoctor`,
	'color1': `Верхний цвет`,
	'color2': `Средний цвет`,
	'color3': `Нижний цвет`,
	'upTime': `Время набора`,
	'constTime': `Время задержки`,
	'downTime': `Время затухания`,
	'speed': `Скорость`,

	// Слоганы главной страницы
	'sloganTitle1': `Далеко-далеко за словесными горами.`,
	'slogan1': `Далеко-далеко за словесными горами в стране гласных и согласных живут
          рыбные тексты. Языкового агентство над приставка города до последний
          назад переписали большой собрал путь напоивший бросил прямо свою
          текстов, семантика домах жаренные возвращайся. Толку, рекламных. Пояс
          знаках до предупреждал рекламных сбить напоивший даже на берегу
          вопроса, силуэт великий текст живет приставка родного строчка?`,
	// 'slogan2': ``, // no phrase provided - fallback to default
	// 'slogan3': ``, // no phrase provided - fallback to default

}